@php
    $report = $report ?? [];
@endphp

<table class="meta-grid">
    <tr>
        <td>
            <div class="meta-card">
                <div class="meta-label">{{ db_trans('scope') ?: 'Scope' }}</div>
                <div class="meta-value">{{ data_get($report, 'scope_name', '-') }}</div>
            </div>
        </td>
        <td>
            <div class="meta-card">
                <div class="meta-label">{{ db_trans('period') ?: 'Period' }}</div>
                <div class="meta-value">{{ data_get($report, 'period_label', '-') }}</div>
            </div>
        </td>
        <td>
            <div class="meta-card">
                <div class="meta-label">{{ db_trans('generated_on') ?: 'Generated On' }}</div>
                <div class="meta-value">{{ data_get($report, 'generated_at', '-') }}</div>
            </div>
        </td>
        <td>
            <div class="meta-card">
                <div class="meta-label">{{ db_trans('generated_by') ?: 'Generated By' }}</div>
                <div class="meta-value">{{ data_get($report, 'generated_by', '-') }}</div>
            </div>
        </td>
    </tr>
</table>
