@extends('layouts.admin')
@section('title', db_trans('blocked_dates'))
@push('styles')<link rel="stylesheet" href="{{ asset('admin/css/hall-booking-v1.css') }}"><link rel="stylesheet" href="https://cdn.datatables.net/1.13.8/css/dataTables.bootstrap5.min.css">@endpush
@section('content')
<div class="hall-booking-module"><section class="hb-hero hb-hero-compact mb-4"><div><h2 class="hb-hero-title">{{ db_trans('blocked_dates') }}</h2><p class="hb-hero-subtitle">{{ db_trans('block_hall_dates_for_internal_use_or_maintenance') }}</p></div><button class="btn btn-light btn-sm" data-bs-toggle="modal" data-bs-target="#createBlockedDateModal"><i class="fas fa-plus me-1"></i>{{ db_trans('add_blocked_date') }}</button></section>
<div class="card hb-panel border-0"><div class="card-body"><table class="table hb-table" id="hbBlockedDatesTable"><thead><tr><th>{{ db_trans('hall') }}</th><th>{{ db_trans('date') }}</th><th>{{ db_trans('reason') }}</th><th>{{ db_trans('created_by') }}</th><th>{{ db_trans('actions') }}</th></tr></thead><tbody>@foreach($blockedDates as $row)<tr><td>{{ $row->hall?->name }}</td><td>{{ $row->blocked_date?->format('d M Y') }}</td><td>{{ $row->reason ?: '-' }}</td><td>{{ $row->creator?->name ?: '-' }}</td><td><form method="POST" action="{{ route('hall-bookings.blocked-dates.destroy',$row) }}" data-confirm-delete>@csrf @method('DELETE')<button class="btn btn-sm btn-outline-danger">{{ db_trans('delete') }}</button></form></td></tr>@endforeach</tbody></table></div></div>
<div class="modal fade" id="createBlockedDateModal" tabindex="-1"><div class="modal-dialog modal-dialog-centered"><div class="modal-content border-0 hb-modal"><form method="POST" action="{{ route('hall-bookings.blocked-dates.store') }}">@csrf <div class="modal-header"><h5>{{ db_trans('add_blocked_date') }}</h5><button type="button" class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="mb-3"><label class="form-label">{{ db_trans('hall') }}</label><select name="hall_id" class="form-select" required>@foreach($halls as $hall)<option value="{{ $hall->id }}">{{ $hall->name }}</option>@endforeach</select></div><div class="mb-3"><label class="form-label">{{ db_trans('date') }}</label><input type="date" name="blocked_date" class="form-control" required></div><div class="mb-3"><label class="form-label">{{ db_trans('reason') }}</label><textarea name="reason" class="form-control"></textarea></div></div><div class="modal-footer"><button type="button" class="btn btn-light" data-bs-dismiss="modal">{{ db_trans('close') }}</button><button class="btn btn-primary">{{ db_trans('save') }}</button></div></form></div></div></div>
</div>
@endsection
@push('scripts')<script src="https://cdn.datatables.net/1.13.8/js/jquery.dataTables.min.js"></script><script src="https://cdn.datatables.net/1.13.8/js/dataTables.bootstrap5.min.js"></script><script src="{{ asset('admin/js/hall-booking-v1.js') }}"></script>@endpush
