@extends('layouts.admin')
@section('title', db_trans('sermons'))
@push('styles')<link rel="stylesheet" href="{{ asset('admin/css/sermons-module-v1.css') }}"><link rel="stylesheet" href="https://cdn.datatables.net/1.13.8/css/dataTables.bootstrap5.min.css">@endpush
@section('content')
<div class="sermons-module">
    <div class="sermon-hero sermon-hero-compact"><div><h2 class="sermon-hero-title">{{ db_trans('sermons') }}</h2><p class="sermon-hero-subtitle">{{ db_trans('manage_sermons_and_secure_links') }}</p></div>@can('sermons.create')<a class="btn btn-light btn-sm" href="{{ route('sermons.create') }}"><i class="fas fa-plus me-1"></i>{{ db_trans('write_sermon') }}</a>@endcan</div>
    <div class="card sermon-panel border-0"><div class="card-body"><div class="table-responsive"><table id="sermonsTable" class="table sermon-table align-middle"><thead><tr><th>{{ db_trans('title') }}</th><th>{{ db_trans('status') }}</th><th>{{ db_trans('recipients') }}</th><th>{{ db_trans('views') }}</th><th>{{ db_trans('actions') }}</th></tr></thead><tbody>
    @foreach($sermons as $sermon)<tr><td><strong>{{ $sermon->title }}</strong><div class="small text-muted">{{ $sermon->created_at->format('d M Y') }}</div></td><td><span class="sermon-status sermon-status-{{ $sermon->status }}">{{ db_trans('sermon_status_'.$sermon->status) }}</span></td><td>{{ $sermon->recipients_count }}</td><td>{{ $sermon->views_count }}</td><td><div class="d-flex gap-2 flex-wrap"><a href="{{ route('sermons.edit',$sermon) }}" class="btn btn-sm btn-outline-primary">{{ db_trans('edit') }}</a>@can('sermons.publish')<form method="POST" action="{{ route('sermons.publish',$sermon) }}">@csrf<button class="btn btn-sm btn-success">{{ db_trans('publish') }}</button></form>@endcan @can('sermons.send_sms')<form method="POST" action="{{ route('sermons.send-links',$sermon) }}">@csrf<button class="btn btn-sm btn-info text-white">{{ db_trans('send_sms') }}</button></form>@endcan @can('sermons.deactivate')<form method="POST" action="{{ route('sermons.deactivate',$sermon) }}">@csrf<button class="btn btn-sm btn-warning">{{ db_trans('deactivate') }}</button></form>@endcan @can('sermons.delete')<form method="POST" action="{{ route('sermons.destroy',$sermon) }}" data-sermon-confirm-delete>@csrf @method('DELETE')<button class="btn btn-sm btn-danger">{{ db_trans('delete') }}</button></form>@endcan</div></td></tr>@endforeach
    </tbody></table></div></div></div>
</div>
@endsection
@push('scripts')<script src="https://code.jquery.com/jquery-3.7.1.min.js"></script><script src="https://cdn.datatables.net/1.13.8/js/jquery.dataTables.min.js"></script><script src="https://cdn.datatables.net/1.13.8/js/dataTables.bootstrap5.min.js"></script><script src="{{ asset('admin/js/sermons-module-v1.js') }}"></script>@endpush
