<div class="modal fade" id="{{ $modalId }}" tabindex="-1" aria-hidden="true"><div class="modal-dialog modal-lg modal-dialog-centered"><div class="modal-content border-0 hb-modal"><form method="POST" action="{{ $action }}">@csrf @if($rule) @method('PUT') @endif <div class="modal-header"><h5>{{ $title }}</h5><button type="button" class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="row g-3">
<div class="col-md-6"><label class="form-label">{{ db_trans('hall') }}</label><select name="hall_id" class="form-select" required>@foreach($halls as $hall)<option value="{{ $hall->id }}" @selected(old('hall_id',$rule?->hall_id)==$hall->id)>{{ $hall->name }}</option>@endforeach</select></div>
<div class="col-md-6"><label class="form-label">{{ db_trans('rule_type') }}</label><select name="rule_type" class="form-select hb-rule-type"><option value="weekly" @selected(!$rule?->specific_date)>{{ db_trans('weekly') }}</option><option value="specific_date" @selected((bool)$rule?->specific_date)>{{ db_trans('special_date') }}</option></select></div>
<div class="col-md-6 hb-weekly-field"><label class="form-label">{{ db_trans('day_of_week') }}</label><select name="day_of_week" class="form-select">@foreach($weekDays as $key=>$label)<option value="{{ $key }}" @selected((string)old('day_of_week',$rule?->day_of_week)===(string)$key)>{{ $label }}</option>@endforeach</select></div>
<div class="col-md-6 hb-date-field"><label class="form-label">{{ db_trans('specific_date') }}</label><input type="date" name="specific_date" class="form-control" value="{{ old('specific_date',$rule?->specific_date?->toDateString()) }}"></div>
<div class="col-md-4"><label class="form-label">{{ db_trans('price') }}</label><input type="number" step="0.01" name="price" class="form-control" required value="{{ old('price',$rule?->price ?? 0) }}"></div>
<div class="col-md-4"><label class="form-label">{{ db_trans('effective_from') }}</label><input type="date" name="effective_from" class="form-control" value="{{ old('effective_from',$rule?->effective_from?->toDateString()) }}"></div>
<div class="col-md-4"><label class="form-label">{{ db_trans('effective_to') }}</label><input type="date" name="effective_to" class="form-control" value="{{ old('effective_to',$rule?->effective_to?->toDateString()) }}"></div>
<div class="col-12"><label class="form-check"><input type="checkbox" name="is_active" value="1" class="form-check-input" @checked(old('is_active',$rule?->is_active ?? true))> {{ db_trans('active') }}</label></div>
</div></div><div class="modal-footer"><button type="button" class="btn btn-light" data-bs-dismiss="modal">{{ db_trans('close') }}</button><button class="btn btn-primary">{{ db_trans('save') }}</button></div></form></div></div></div>
