@extends('layouts.admin')
@section('title', db_trans('bookings'))
@push('styles')<link rel="stylesheet" href="{{ asset('admin/css/hall-booking-v1.css') }}"><link rel="stylesheet" href="https://cdn.datatables.net/1.13.8/css/dataTables.bootstrap5.min.css">@endpush
@section('content')
<div class="hall-booking-module"><section class="hb-hero hb-hero-compact mb-4"><div><h2 class="hb-hero-title">{{ db_trans('bookings') }}</h2><p class="hb-hero-subtitle">{{ db_trans('manage_hall_booking_requests_payment_verification_and_status') }}</p></div>@can('hall-bookings.bookings.update')<button class="btn btn-light btn-sm" data-bs-toggle="modal" data-bs-target="#createBookingModal"><i class="fas fa-plus me-1"></i>{{ db_trans('add_booking') }}</button>@endcan</section>
<div class="card hb-panel border-0 mb-4"><div class="card-body"><form method="GET" class="row g-3 align-items-end"><div class="col-md-3"><label class="form-label">{{ db_trans('hall') }}</label><select name="hall_id" class="form-select"><option value="">{{ db_trans('all') }}</option>@foreach($halls as $hall)<option value="{{ $hall->id }}" @selected(request('hall_id')==$hall->id)>{{ $hall->name }}</option>@endforeach</select></div><div class="col-md-2"><label class="form-label">{{ db_trans('booking_status') }}</label><select name="status" class="form-select"><option value="">{{ db_trans('all') }}</option>@foreach($bookingStatuses as $status)<option value="{{ $status }}" @selected(request('status')===$status)>{{ db_trans('hall_booking_status_'.$status) }}</option>@endforeach</select></div><div class="col-md-2"><label class="form-label">{{ db_trans('payment_status') }}</label><select name="payment_status" class="form-select"><option value="">{{ db_trans('all') }}</option>@foreach($paymentStatuses as $status)<option value="{{ $status }}" @selected(request('payment_status')===$status)>{{ db_trans('hall_payment_status_'.$status) }}</option>@endforeach</select></div><div class="col-md-2"><label class="form-label">{{ db_trans('from_date') }}</label><input type="date" name="from_date" value="{{ request('from_date') }}" class="form-control"></div><div class="col-md-2"><label class="form-label">{{ db_trans('to_date') }}</label><input type="date" name="to_date" value="{{ request('to_date') }}" class="form-control"></div><div class="col-md-1"><button class="btn btn-primary w-100"><i class="fas fa-filter"></i></button></div></form></div></div>
<div class="card hb-panel border-0"><div class="card-body"><div class="table-responsive"><table class="table hb-table align-middle" id="hbBookingsTable"><thead><tr><th>{{ db_trans('reference') }}</th><th>{{ db_trans('customer') }}</th><th>{{ db_trans('phone') }}</th><th>{{ db_trans('hall') }}</th><th>{{ db_trans('date') }}</th><th>{{ db_trans('price') }}</th><th>{{ db_trans('booking_status') }}</th><th>{{ db_trans('payment_status') }}</th><th>{{ db_trans('actions') }}</th></tr></thead><tbody>
@foreach($bookings as $booking)<tr><td><a class="fw-bold" href="{{ route('hall-bookings.bookings.show',$booking) }}">{{ $booking->booking_reference }}</a></td><td>{{ $booking->customer_name }}</td><td>{{ $booking->customer_phone }}</td><td>{{ $booking->hall?->name }}</td><td>{{ $booking->booking_date?->format('d M Y') }}</td><td>{{ number_format((float)$booking->price,2) }}</td><td><span class="hb-status hb-status-{{ $booking->booking_status }}">{{ db_trans($booking->booking_status_label_key) }}</span></td><td><span class="hb-status hb-pay-{{ $booking->payment_status }}">{{ db_trans($booking->payment_status_label_key) }}</span></td><td><div class="d-flex gap-2 flex-wrap"><a class="btn btn-sm btn-outline-primary" href="{{ route('hall-bookings.bookings.show',$booking) }}">{{ db_trans('view') }}</a>@can('hall-bookings.bookings.verify-payment')<form method="POST" action="{{ route('hall-bookings.bookings.verify-payment',$booking) }}">@csrf <button class="btn btn-sm btn-outline-success">{{ db_trans('verify') }}</button></form>@endcan</div></td></tr>@endforeach
</tbody></table></div></div></div>
@include('admin.hall-bookings.bookings.partials.create-modal')
</div>
@endsection
@push('scripts')<script src="https://cdn.datatables.net/1.13.8/js/jquery.dataTables.min.js"></script><script src="https://cdn.datatables.net/1.13.8/js/dataTables.bootstrap5.min.js"></script><script src="{{ asset('admin/js/hall-booking-v1.js') }}"></script>@endpush
